[build-system]
requires = [
    "setuptools>=61.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "dvae"
version = "0.1.0"
description = "Denoising Variational Auto-Encoder (DVAE) for binary classification in extremely low-data regimes."
readme = "README.md"
requires-python = ">=3.10,<3.13"
license = { text = "Apache-2.0" }

authors = [
    { name = "Radim Nedbal" }
]

# --- Runtime dependencies (installed automatically when user installs the wheel) ---
dependencies = [
    "numpy<2",
    "torch==2.2.2",
    "pyro-ppl==1.9.1",
    "scikit-learn==1.7.2"
]

[project.urls]
Homepage = "https://github.com/rdned/DVAE"
Repository = "https://github.com/rdned/DVAE"