[build-system]
requires = ["setuptools>=61", "setuptools_scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/dvae/_version.py"

[project]
name = "dvae"
dynamic = ["version"]
description = "Denoising Variational Auto-Encoder (DVAE) for binary classification in extremely low-data regimes."
readme = "README.md"
requires-python = ">=3.10,<3.12"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]

authors = [
    { name = "Radim Nedbal" }
]

dependencies = [
    "numpy<2",
    "torch==2.2.2",
    "pyro-ppl==1.9.1",
    "scikit-learn==1.7.2"
]

[project.optional-dependencies]
dev = [
    "pre-commit",
]

[project.urls]
Homepage = "https://github.com/rdned/DVAE"
Repository = "https://github.com/rdned/DVAE"
